version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/dealer_inspire
      - /srv/dealer_inspire/vendor
    ports:
      - "9999:9999"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: dealer_inspire
      DB_USERNAME: dev
      DB_PASSWORD: dev

  db:
    image: mysql:5.6.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dealer_inspire
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      - dealer_inspire_mysql:/var/lib/mysql
      - ./database/initializers/my.cnf:/etc/mysql/my.cnf

volumes:
  dealer_inspire_mysql: