version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/dealer_inspire
      - /srv/dealer_inspire/vendor
    ports:
      - "9999:9999"
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dealer_inspire
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - dealer_inspire_mysql:/var/lib/mysql

volumes:
  dealer_inspire_mysql: